package config

import (
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/lugoues/borgmatic-manager/internal/models"
)

const headerComment = "# Auto-generated by borgmatic-manager. Do not edit.\n"

// snapshotHookKeys are the borgmatic filesystem snapshot hooks. Their presence
// in a group's merged config means concurrent runs could destroy each other's
// snapshots (borgmatic's cleanup is name-prefix-matched), so such groups must
// serialize globally.
var snapshotHookKeys = []string{"btrfs", "zfs", "lvm"}

// defaultArchiveNameFormat: {group} is substituted by the manager, the rest by borg.
const defaultArchiveNameFormat = "{hostname}-{group}-{now:%Y-%m-%d_%H:%M}"

// GroupRunMeta is scheduling metadata extracted from a group's generated config.
type GroupRunMeta struct {
	// Repos are canonicalized repository keys. Groups sharing a key must not
	// run concurrently (Borg 1.x locks repositories exclusively).
	Repos []string
	// SnapshotHooks is true when the config enables btrfs/zfs/lvm hooks.
	SnapshotHooks bool
}

// GeneratorOptions carries host-environment facts the generator needs.
type GeneratorOptions struct {
	// RuntimeDir is pinned as borgmatic's user_runtime_directory; helper dump
	// containers bind-mount it to reach borgmatic's dump FIFOs.
	RuntimeDir string
	// StateDir is pinned as borgmatic's user_state_directory (check-frequency
	// records). Relocating it makes borgmatic re-run all checks.
	StateDir string
	// ContainerCLI is the container CLI binary ("docker" or "podman") used in
	// generated helper/exec dump commands. Empty defaults to "docker".
	ContainerCLI string
}

// Generator produces per-group borgmatic YAML configuration files.
type Generator struct {
	cfg            *ManagerConfig
	groupOverrides map[string]map[string]interface{}
	outputDir      string
	opts           GeneratorOptions
	logger         *slog.Logger

	// lookPath is an exec.LookPath seam for testing host-dependency warnings.
	lookPath func(string) (string, error)
}

// NewGenerator creates a Generator. Generated files are written atomically to
// outputDir/{group}.yaml with 0600 permissions.
func NewGenerator(cfg *ManagerConfig, groupOverrides map[string]map[string]interface{}, outputDir string, opts GeneratorOptions, logger *slog.Logger) *Generator {
	return &Generator{
		cfg:            cfg,
		groupOverrides: groupOverrides,
		outputDir:      outputDir,
		opts:           opts,
		logger:         logger,
		lookPath:       exec.LookPath,
	}
}

// Refusal names a group that generation refused, and why.
type Refusal struct {
	Group  string
	Reason string
}

// Generate writes a borgmatic config per group and returns scheduling metadata.
// The output directory is reconciled: configs for removed groups are deleted.
func (g *Generator) Generate(state *models.BackupState) (map[string]GroupRunMeta, error) {
	if err := os.MkdirAll(g.outputDir, 0o700); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	// Sort group names for deterministic output order.
	groupNames := make([]string, 0, len(state.Groups))
	for name := range state.Groups {
		groupNames = append(groupNames, name)
	}
	sort.Strings(groupNames)

	entries, _, err := g.plan(state, groupNames)
	if err != nil {
		return nil, err
	}

	// Pass 3: write the surviving configs.
	meta := make(map[string]GroupRunMeta, len(entries))
	written := make([]string, 0, len(entries))
	for _, e := range entries {
		yamlData, err := yaml.Marshal(e.final)
		if err != nil {
			return nil, fmt.Errorf("marshaling config for group %s: %w", e.name, err)
		}
		output := append([]byte(headerComment), yamlData...)

		// 0600: generated configs carry credentials.
		outPath := filepath.Join(g.outputDir, e.name+".yaml")
		if err := writeFileAtomic(outPath, output, 0o600); err != nil {
			return nil, fmt.Errorf("writing config for group %s: %w", e.name, err)
		}

		meta[e.name] = e.meta
		written = append(written, e.name)
	}

	if err := g.reconcile(written); err != nil {
		return nil, err
	}

	return meta, nil
}

// Plan runs generation's build and safety passes without writing anything,
// returning scheduling metadata and refusals.
func (g *Generator) Plan(state *models.BackupState) (map[string]GroupRunMeta, []Refusal, error) {
	groupNames := make([]string, 0, len(state.Groups))
	for name := range state.Groups {
		groupNames = append(groupNames, name)
	}
	sort.Strings(groupNames)

	entries, refusals, err := g.plan(state, groupNames)
	if err != nil {
		return nil, nil, err
	}
	meta := make(map[string]GroupRunMeta, len(entries))
	for _, e := range entries {
		meta[e.name] = e.meta
	}
	return meta, refusals, nil
}

// pending is one group's fully merged config awaiting the write pass.
type pending struct {
	name  string
	final map[string]interface{}
	meta  GroupRunMeta
}

// plan builds every group's final config in memory (pass 1) and applies
// cross-group safety checks (pass 2), returning survivors and refusals.
func (g *Generator) plan(state *models.BackupState, groupNames []string) ([]*pending, []Refusal, error) {
	// Pass 1: build every group's final config in memory.
	entries := make([]*pending, 0, len(groupNames))

	for _, groupName := range groupNames {
		group := state.Groups[groupName]

		// 1. Deep copy global defaults via marshal/unmarshal.
		base, err := deepCopyMap(g.cfg.Borgmatic)
		if err != nil {
			return nil, nil, fmt.Errorf("copying defaults for group %s: %w", groupName, err)
		}

		// 2. Apply per-group overrides if present.
		if g.groupOverrides != nil {
			if override, ok := g.groupOverrides[groupName]; ok {
				base = DeepMerge(base, override)
			}
		}

		// 2b. Apply label config fragments: labels win over files, discovered
		// data wins over both.
		for _, labelCfg := range group.LabelConfigs {
			warnLabelHooks(groupName, labelCfg, g.logger)
			base = DeepMerge(base, labelCfg)
		}

		// 3. Build discovered data from volumes and databases. Volume-named
		// archive paths (the /./ marker) are disabled when snapshot hooks
		// are enabled: the hooks construct their own /./ rewrites and borg
		// allows only one marker per path.
		discovered := g.buildDiscoveredData(groupName, group, !hasSnapshotHooks(base))

		// 4. Merge discovered data on top (discovered wins).
		final := DeepMerge(base, discovered)

		// 5. Archive naming: the user's format wins when set; "{group}" is
		// substituted by the manager (all other {...} are borg placeholders).
		format, _ := final["archive_name_format"].(string)
		if format == "" {
			format = defaultArchiveNameFormat
		}
		final["archive_name_format"] = strings.ReplaceAll(format, "{group}", groupName)

		entries = append(entries, &pending{
			name:  groupName,
			final: final,
			meta: GroupRunMeta{
				Repos:         extractRepoKeys(final),
				SnapshotHooks: hasSnapshotHooks(final),
			},
		})
	}

	// Pass 2: groups sharing a repository must keep distinguishable archive names,
	// or one group's retention (match_archives derives from the format) prunes another's.
	repoGroups := make(map[string][]string)
	for _, e := range entries {
		for _, repo := range e.meta.Repos {
			repoGroups[repo] = append(repoGroups[repo], e.name)
		}
	}

	var refusals []Refusal
	kept := entries[:0]
	for _, e := range entries {
		sharesRepo := false
		for _, repo := range e.meta.Repos {
			if len(repoGroups[repo]) > 1 {
				sharesRepo = true
				break
			}
		}
		format, _ := e.final["archive_name_format"].(string)
		if sharesRepo && !strings.Contains(format, e.name) {
			g.logger.Error("archive_name_format must contain the group name (use the {group} token) when groups share a repository, retention for one group would otherwise prune the others' archives; skipping group",
				"group", e.name, "archive_name_format", format)
			refusals = append(refusals, Refusal{Group: e.name, Reason: "archive_name_format must contain the group name when groups share a repository"})
			continue
		}
		kept = append(kept, e)
	}

	warnPrefixCollisions(repoGroups, g.logger)

	return kept, refusals, nil
}

// hookKeys are borgmatic options that execute shell commands as the user
// running borgmatic (root under the system unit).
var hookKeys = map[string]bool{
	"commands": true, "before_actions": true, "after_actions": true,
	"before_backup": true, "after_backup": true, "before_prune": true,
	"after_prune": true, "before_check": true, "after_check": true,
	"before_compact": true, "after_compact": true, "before_extract": true,
	"after_extract": true, "on_error": true, "before_everything": true,
	"after_everything": true,
}

// warnLabelHooks flags command hooks arriving via container labels: anyone who
// can label a container makes borgmatic run them as root. Warns, never blocks.
func warnLabelHooks(groupName string, labelCfg map[string]interface{}, logger *slog.Logger) {
	for key := range labelCfg {
		if hookKeys[key] {
			logger.Warn("label-sourced config defines a command hook: it will run as the manager's user (root), anyone who can label a container controls it",
				"group", groupName, "option", key)
		}
	}
}

// reconcile removes generated configs whose groups no longer exist. Only files
// carrying the generated header are touched; operator YAML is left alone.
func (g *Generator) reconcile(current []string) error {
	keep := make(map[string]bool, len(current))
	for _, name := range current {
		keep[name+".yaml"] = true
	}

	entries, err := os.ReadDir(g.outputDir)
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".yaml") || keep[name] {
			continue
		}
		path := filepath.Join(g.outputDir, name)
		if !hasGeneratedHeader(path) {
			g.logger.Warn("leaving non-generated yaml file alone in output directory", "file", name)
			continue
		}
		if err := os.Remove(path); err != nil {
			g.logger.Warn("failed to remove stale generated config", "file", name, "error", err)
			continue
		}
		g.logger.Info("removed stale generated config", "file", name)
	}
	return nil
}

// hasGeneratedHeader reports whether the file begins with the generated header comment.
func hasGeneratedHeader(path string) bool {
	f, err := os.Open(path) // #nosec G304 -- manager-owned output directory listing
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	buf := make([]byte, len(headerComment))
	n, _ := io.ReadFull(f, buf)
	return string(buf[:n]) == headerComment
}

// buildDiscoveredData constructs a map of configuration values discovered from
// the group's volumes and databases.
func (g *Generator) buildDiscoveredData(groupName string, group *models.VolumeGroup, volumeNamedPaths bool) map[string]interface{} {
	data := map[string]interface{}{}

	// Pin borgmatic's runtime/state dirs to the manager's own; user config can override.
	if g.opts.RuntimeDir != "" {
		data["user_runtime_directory"] = g.opts.RuntimeDir
	}
	if g.opts.StateDir != "" {
		data["user_state_directory"] = g.opts.StateDir
	}

	// Volume-named paths use borg's "/./" marker (borg >= 1.4) so archives
	// record "volA/_data/..." rather than the full /var/lib/docker path.
	if len(group.Volumes) > 0 {
		dirs := make([]interface{}, 0, len(group.Volumes))
		for _, vol := range group.Volumes {
			path := vol.HostPath
			if volumeNamedPaths {
				path = volumeNamedPath(vol.HostPath, vol.Name)
			}
			dirs = append(dirs, path)
		}
		data["source_directories"] = dirs
	}

	dbHooks := g.buildDatabaseHooks(groupName, group.Databases)
	for k, v := range dbHooks {
		data[k] = v
	}

	return data
}

// engineClients maps a database type to host client binaries borgmatic will
// invoke; at least one must be present on the host for dumps to work.
var engineClients = map[string][]string{
	dbTypePostgres: {"pg_dump"},
	dbTypeMySQL:    {mysqldumpBin},
	dbTypeMariaDB:  {"mariadb-dump", mysqldumpBin},
	dbTypeSQLite:   {"sqlite3"},
}

// Database engine types. SQLite entries emit a path, never a connection.
const (
	dbTypePostgres = "postgresql"
	dbTypeMySQL    = "mysql"
	dbTypeMariaDB  = "mariadb"
	dbTypeSQLite   = "sqlite"
)

// mysqldumpBin also serves as MariaDB's fallback dump client.
const mysqldumpBin = "mysqldump"

var engineKey = map[string]string{
	dbTypePostgres: "postgresql_databases",
	dbTypeMySQL:    "mysql_databases",
	dbTypeMariaDB:  "mariadb_databases",
	dbTypeSQLite:   "sqlite_databases",
}

// buildDatabaseHooks emits borgmatic database hook entries: helper container
// (default), hostname (host client), exec (postgresql only), or sqlite (host path).
func (g *Generator) buildDatabaseHooks(groupName string, dbs []models.DatabaseConfig) map[string]interface{} {
	if len(dbs) == 0 {
		return nil
	}

	grouped := make(map[string][]interface{})
	for _, db := range dbs {
		key, ok := engineKey[db.Type]
		if !ok {
			key = db.Type + "_databases"
		}

		entry := map[string]interface{}{
			"name": db.Name,
		}

		switch {
		case db.Type == dbTypeSQLite:
			entry["path"] = db.Path
			g.warnIfMissing(groupName, db.Type, engineClients[db.Type]...)

		case db.Hostname != "":
			entry["hostname"] = db.Hostname
			if db.Port != 0 {
				entry["port"] = db.Port
			}
			g.warnIfMissing(groupName, db.Type, engineClients[db.Type]...)

		default:
			g.buildContainerClientEntry(entry, db)
			g.warnIfMissing(groupName, db.Type, g.containerCLI())
		}

		if db.Username != "" {
			entry["username"] = db.Username
		}
		if db.Password != "" {
			entry["password"] = db.Password
		}
		if db.Options != "" {
			entry["options"] = db.Options
		}

		grouped[key] = append(grouped[key], entry)
	}

	result := make(map[string]interface{}, len(grouped))
	for k, v := range grouped {
		result[k] = v
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

func (g *Generator) containerCLI() string {
	if g.opts.ContainerCLI != "" {
		return g.opts.ContainerCLI
	}
	return "docker"
}

// clientBinaries maps engines to (dump, interact) client binaries used in
// generated helper/exec commands.
var clientBinaries = map[string]struct{ dump, restore, interact string }{
	dbTypePostgres: {"pg_dump", "pg_restore", "psql"},
	dbTypeMySQL:    {mysqldumpBin, "mysql", "mysql"},
	dbTypeMariaDB:  {"mariadb-dump", "mariadb", "mariadb"},
}

// buildContainerClientEntry fills an entry whose client runs in a container
// (helper in the database container's netns, or exec into it). The target is
// always 127.0.0.1; the container name doubles as the borgmatic label.
func (g *Generator) buildContainerClientEntry(entry map[string]interface{}, db models.DatabaseConfig) {
	cli := g.containerCLI()
	bins := clientBinaries[db.Type]

	var base, interactive string
	if db.Mode == "exec" {
		base = fmt.Sprintf("%s exec --env PGPASSWORD %s", cli, db.Container)
		interactive = fmt.Sprintf("%s exec -i --env PGPASSWORD %s", cli, db.Container)
	} else {
		run := fmt.Sprintf("%s run --rm", cli)
		if db.Type == dbTypeMySQL || db.Type == dbTypeMariaDB {
			// Mount the runtime dir at the identical path so the client reaches borgmatic's dump FIFO.
			run += fmt.Sprintf(" -v %s:%s", g.opts.RuntimeDir, g.opts.RuntimeDir)
		}
		envFlag := "--env PGPASSWORD"
		if db.Type != dbTypePostgres {
			envFlag = "--env MYSQL_PWD"
		}
		net := fmt.Sprintf("--network container:%s", db.Container)
		base = fmt.Sprintf("%s %s %s %s", run, net, envFlag, db.Image)
		interactive = fmt.Sprintf("%s -i %s %s %s", run, net, envFlag, db.Image)
	}

	entry["hostname"] = "127.0.0.1"
	if db.Port != 0 {
		entry["port"] = db.Port
	}
	entry["label"] = db.Container

	switch db.Type {
	case dbTypePostgres:
		entry["pg_dump_command"] = base + " " + bins.dump
		entry["pg_restore_command"] = interactive + " " + bins.restore
		entry["psql_command"] = interactive + " " + bins.interact
	case dbTypeMySQL:
		entry["password_transport"] = "environment"
		entry["mysql_dump_command"] = base + " " + bins.dump
		entry["mysql_command"] = interactive + " " + bins.interact
	case dbTypeMariaDB:
		entry["password_transport"] = "environment"
		entry["mariadb_dump_command"] = base + " " + bins.dump
		entry["mariadb_command"] = interactive + " " + bins.interact
	}
}

// volumeNamedPath inserts borg's "/./" marker before the volume-name component
// so archive paths start at the volume name; unmatched paths pass through unchanged.
func volumeNamedPath(hostPath, volumeName string) string {
	marker := string(filepath.Separator) + volumeName
	idx := strings.LastIndex(hostPath, marker+string(filepath.Separator))
	if idx < 0 {
		if strings.HasSuffix(hostPath, marker) {
			idx = len(hostPath) - len(marker)
		} else {
			return hostPath
		}
	}
	return hostPath[:idx] + string(filepath.Separator) + "." + hostPath[idx:]
}

// warnPrefixCollisions flags shared-repo groups where one name prefixes another:
// their match_archives patterns overlap, so retention can cross group boundaries.
func warnPrefixCollisions(repoGroups map[string][]string, logger *slog.Logger) {
	for repo, groups := range repoGroups {
		if len(groups) < 2 {
			continue
		}
		sort.Strings(groups)
		for i, a := range groups {
			for _, b := range groups[i+1:] {
				if strings.HasPrefix(b, a+"-") {
					logger.Warn("group names where one prefixes another share a repository; their archive name patterns overlap and retention can cross group boundaries, rename a group or split repositories",
						"repository", repo, "groups", a+", "+b)
				}
			}
		}
	}
}

// warnIfMissing warns when none of the candidate host binaries are on PATH;
// a missing dump client is a guaranteed runtime failure.
func (g *Generator) warnIfMissing(groupName, dbType string, candidates ...string) {
	if len(candidates) == 0 {
		return
	}
	for _, bin := range candidates {
		if _, err := g.lookPath(bin); err == nil {
			return
		}
	}
	g.logger.Warn("required host binary not found on PATH; database backups for this group will fail until it is installed",
		"group", groupName, "db_type", dbType, "binaries", strings.Join(candidates, " or "))
}

// extractRepoKeys returns canonicalized repository keys: string-equal keys mean
// "same repository" for locking; unresolvable entries collapse to one conservative key.
func extractRepoKeys(final map[string]interface{}) []string {
	repos, ok := final["repositories"].([]interface{})
	if !ok {
		return nil
	}

	seen := make(map[string]bool)
	var keys []string
	for _, r := range repos {
		var path string
		switch v := r.(type) {
		case string:
			path = v
		case map[string]interface{}:
			path, _ = v["path"].(string)
		}
		if path == "" {
			continue
		}
		key := canonicalRepoKey(path)
		if !seen[key] {
			seen[key] = true
			keys = append(keys, key)
		}
	}
	return keys
}

// canonicalRepoKey normalizes a repository path for use as a lock key.
func canonicalRepoKey(path string) string {
	if strings.Contains(path, "${") {
		// Env placeholders resolve at borgmatic runtime; two spellings could
		// be the same repo. Serialize conservatively under one key.
		return "unknown"
	}
	if strings.Contains(path, "://") || strings.Contains(path, "@") {
		// Remote URL or user@host:path form.
		return strings.TrimRight(path, "/")
	}
	cleaned := filepath.Clean(path)
	if resolved, err := filepath.EvalSymlinks(cleaned); err == nil {
		return resolved
	}
	return cleaned
}

// hasSnapshotHooks reports whether the config enables any filesystem snapshot
// hook. Key presence counts: a bare `btrfs:` maps to a nil value.
func hasSnapshotHooks(final map[string]interface{}) bool {
	for _, key := range snapshotHookKeys {
		if _, ok := final[key]; ok {
			return true
		}
	}
	return false
}

// deepCopyMap creates a deep copy of a map by marshaling and unmarshaling.
func deepCopyMap(m map[string]interface{}) (map[string]interface{}, error) {
	if m == nil {
		return make(map[string]interface{}), nil
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result map[string]interface{}
	if err := yaml.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	if result == nil {
		result = make(map[string]interface{})
	}
	return result, nil
}

// writeFileAtomic writes data to a file atomically by writing to a temporary
// file in the same directory and renaming it to the final path.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".borgmatic-*.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}

	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("setting file permissions: %w", err)
	}

	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}

	return nil
}
