package config_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lugoues/borgmatic-manager/internal/config"
	"github.com/lugoues/borgmatic-manager/internal/models"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestGenerateConfigsBasic(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("web", models.VolumeInfo{Name: "web_data", HostPath: "/mnt/web_data"})
	state.AddVolume("web", models.VolumeInfo{Name: "web_assets", HostPath: "/mnt/web_assets"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "web.yaml"))
	require.NoError(t, err)

	// Parse YAML (skip header comment)
	var parsed map[string]interface{}
	err = yaml.Unmarshal(data, &parsed)
	require.NoError(t, err)

	srcDirs, ok := parsed["source_directories"].([]interface{})
	require.True(t, ok, "source_directories should be a list")
	assert.Contains(t, srcDirs, "/mnt/web_data")
	assert.Contains(t, srcDirs, "/mnt/web_assets")
	assert.Equal(t, "/mnt/sources", parsed["working_directory"])
}

func TestGenerateConfigsArchiveNameFormat(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("myapp", models.VolumeInfo{Name: "app_vol", HostPath: "/mnt/app"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "myapp.yaml"))
	require.NoError(t, err)

	var parsed map[string]interface{}
	err = yaml.Unmarshal(data, &parsed)
	require.NoError(t, err)

	format, ok := parsed["archive_name_format"].(string)
	require.True(t, ok)
	assert.Equal(t, "{hostname}-myapp-{now:%Y-%m-%d_%H:%M}", format)
}

func TestGenerateConfigsDatabaseHooks(t *testing.T) {
	state := models.NewBackupState()
	state.AddDatabases("db-group", []models.DatabaseConfig{
		{Type: "postgresql", Name: "appdb", Hostname: "pg-host", Username: "pguser"},
		{Type: "mysql", Name: "legacydb", Hostname: "mysql-host", Username: "root"},
		{Type: "postgresql", Name: "analyticsdb", Hostname: "pg-host", Username: "pguser"},
	})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "db-group.yaml"))
	require.NoError(t, err)

	var parsed map[string]interface{}
	err = yaml.Unmarshal(data, &parsed)
	require.NoError(t, err)

	// Check postgresql_databases
	pgDBs, ok := parsed["postgresql_databases"].([]interface{})
	require.True(t, ok, "should have postgresql_databases")
	assert.Len(t, pgDBs, 2)

	// Check mysql_databases
	myDBs, ok := parsed["mysql_databases"].([]interface{})
	require.True(t, ok, "should have mysql_databases")
	assert.Len(t, myDBs, 1)
}

func TestGenerateConfigsDeepMerge(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("app", models.VolumeInfo{Name: "data", HostPath: "/mnt/data"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{
			"keep_daily":   7,
			"keep_weekly":  4,
			"keep_monthly": 6,
		},
	}

	// Group override changes keep_daily
	overrides := map[string]map[string]interface{}{
		"app": {
			"keep_daily": 14,
		},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, overrides, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "app.yaml"))
	require.NoError(t, err)

	var parsed map[string]interface{}
	err = yaml.Unmarshal(data, &parsed)
	require.NoError(t, err)

	// Override should win
	assert.Equal(t, 14, parsed["keep_daily"])
	// Default should remain
	assert.Equal(t, 4, parsed["keep_weekly"])
	assert.Equal(t, 6, parsed["keep_monthly"])
	// Discovered data should be present
	assert.Equal(t, "/mnt/sources", parsed["working_directory"])
}

func TestGenerateConfigsHeader(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("test", models.VolumeInfo{Name: "vol", HostPath: "/mnt/vol"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "test.yaml"))
	require.NoError(t, err)

	content := string(data)
	assert.True(t, strings.HasPrefix(content, "# Auto-generated by borgmatic-manager. Do not edit.\n"),
		"file should start with auto-generated header comment, got: %s", content[:min(len(content), 80)])
}

func TestGenerateConfigsMultipleGroups(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("alpha", models.VolumeInfo{Name: "a_vol", HostPath: "/mnt/a"})
	state.AddVolume("beta", models.VolumeInfo{Name: "b_vol", HostPath: "/mnt/b"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	_, err = os.Stat(filepath.Join(outDir, "alpha.yaml"))
	assert.NoError(t, err, "alpha.yaml should exist")

	_, err = os.Stat(filepath.Join(outDir, "beta.yaml"))
	assert.NoError(t, err, "beta.yaml should exist")
}

func TestGenerateConfigsOmitempty(t *testing.T) {
	state := models.NewBackupState()
	state.AddVolume("minimal", models.VolumeInfo{Name: "vol", HostPath: "/mnt/vol"})

	cfg := &config.ManagerConfig{
		Borgmatic: map[string]interface{}{},
	}

	outDir := t.TempDir()
	err := config.GenerateConfigs(state, cfg, nil, outDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(outDir, "minimal.yaml"))
	require.NoError(t, err)

	content := string(data)
	// No databases were added, so these keys should not appear
	assert.NotContains(t, content, "postgresql_databases")
	assert.NotContains(t, content, "mysql_databases")
	assert.NotContains(t, content, "mariadb_databases")
	assert.NotContains(t, content, "sqlite_databases")
}
