package config

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/lugoues/borgmatic-manager/internal/models"
)

const headerComment = "# Auto-generated by borgmatic-manager. Do not edit.\n"

// snapshotHookKeys are the borgmatic filesystem snapshot hooks. Their presence
// in a group's merged config means concurrent runs could destroy each other's
// snapshots (borgmatic's cleanup is name-prefix-matched), so such groups must
// serialize globally.
var snapshotHookKeys = []string{"btrfs", "zfs", "lvm"}

// GroupRunMeta is scheduling metadata extracted from a group's generated config.
type GroupRunMeta struct {
	// Repos are canonicalized repository keys. Groups sharing a key must not
	// run concurrently (Borg 1.x locks repositories exclusively).
	Repos []string
	// SnapshotHooks is true when the config enables btrfs/zfs/lvm hooks.
	SnapshotHooks bool
}

// GeneratorOptions carries host-environment facts the generator needs.
type GeneratorOptions struct {
	// RuntimeDir is pinned as borgmatic's user_runtime_directory (dump FIFOs,
	// zfs snapshot mounts). Usually the manager's own RuntimeDirectory.
	RuntimeDir string
	// StateDir is pinned as borgmatic's user_state_directory (check-frequency
	// records). Relocating it makes borgmatic re-run all checks.
	StateDir string
	// Rootless indicates a rootless container engine. Rootless (userspace)
	// networking has no host-reachable container IPs, so container-mode
	// database connections are refused at generation time.
	Rootless bool
}

// Generator produces per-group borgmatic YAML configuration files.
type Generator struct {
	cfg            *ManagerConfig
	groupOverrides map[string]map[string]interface{}
	outputDir      string
	opts           GeneratorOptions
	logger         *slog.Logger

	// lookPath is an exec.LookPath seam for testing host-dependency warnings.
	lookPath func(string) (string, error)
}

// NewGenerator creates a Generator. Generated files are written atomically to
// outputDir/{group}.yaml with 0600 permissions.
func NewGenerator(cfg *ManagerConfig, groupOverrides map[string]map[string]interface{}, outputDir string, opts GeneratorOptions, logger *slog.Logger) *Generator {
	return &Generator{
		cfg:            cfg,
		groupOverrides: groupOverrides,
		outputDir:      outputDir,
		opts:           opts,
		logger:         logger,
		lookPath:       exec.LookPath,
	}
}

// Generate writes a borgmatic config per group and returns scheduling metadata.
// The output directory is reconciled: configs for removed groups are deleted.
func (g *Generator) Generate(state *models.BackupState) (map[string]GroupRunMeta, error) {
	if err := os.MkdirAll(g.outputDir, 0o700); err != nil {
		return nil, fmt.Errorf("creating output directory: %w", err)
	}

	// Sort group names for deterministic output order.
	groupNames := make([]string, 0, len(state.Groups))
	for name := range state.Groups {
		groupNames = append(groupNames, name)
	}
	sort.Strings(groupNames)

	meta := make(map[string]GroupRunMeta, len(groupNames))

	for _, groupName := range groupNames {
		group := state.Groups[groupName]

		// 1. Deep copy global defaults via marshal/unmarshal.
		base, err := deepCopyMap(g.cfg.Borgmatic)
		if err != nil {
			return nil, fmt.Errorf("copying defaults for group %s: %w", groupName, err)
		}

		// 2. Apply per-group overrides if present.
		if g.groupOverrides != nil {
			if override, ok := g.groupOverrides[groupName]; ok {
				base = DeepMerge(base, override)
			}
		}

		// 3. Build discovered data from volumes and databases.
		discovered := g.buildDiscoveredData(groupName, group)

		// 4. Merge discovered data on top (discovered wins).
		final := DeepMerge(base, discovered)

		// 5. Marshal to YAML.
		yamlData, err := yaml.Marshal(final)
		if err != nil {
			return nil, fmt.Errorf("marshaling config for group %s: %w", groupName, err)
		}

		// 6. Prepend header comment.
		output := append([]byte(headerComment), yamlData...)

		// 7. Write atomically. 0600: generated configs carry credentials.
		outPath := filepath.Join(g.outputDir, groupName+".yaml")
		if err := writeFileAtomic(outPath, output, 0o600); err != nil {
			return nil, fmt.Errorf("writing config for group %s: %w", groupName, err)
		}

		meta[groupName] = GroupRunMeta{
			Repos:         extractRepoKeys(final),
			SnapshotHooks: hasSnapshotHooks(final),
		}
	}

	if err := g.reconcile(groupNames); err != nil {
		return nil, err
	}

	return meta, nil
}

// reconcile removes generated configs whose groups no longer exist.
func (g *Generator) reconcile(current []string) error {
	keep := make(map[string]bool, len(current))
	for _, name := range current {
		keep[name+".yaml"] = true
	}

	entries, err := os.ReadDir(g.outputDir)
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".yaml") || keep[name] {
			continue
		}
		if err := os.Remove(filepath.Join(g.outputDir, name)); err != nil {
			g.logger.Warn("failed to remove stale generated config", "file", name, "error", err)
			continue
		}
		g.logger.Info("removed stale generated config", "file", name)
	}
	return nil
}

// buildDiscoveredData constructs a map of configuration values discovered from
// the group's volumes and databases.
func (g *Generator) buildDiscoveredData(groupName string, group *models.VolumeGroup) map[string]interface{} {
	data := map[string]interface{}{
		"archive_name_format": fmt.Sprintf("{hostname}-%s-{now:%%Y-%%m-%%d_%%H:%%M}", groupName),
	}

	// Pin borgmatic's runtime/state dirs to the manager's own; user config can override.
	if g.opts.RuntimeDir != "" {
		data["user_runtime_directory"] = g.opts.RuntimeDir
	}
	if g.opts.StateDir != "" {
		data["user_state_directory"] = g.opts.StateDir
	}

	// Source directories from volume host paths.
	if len(group.Volumes) > 0 {
		dirs := make([]interface{}, 0, len(group.Volumes))
		for _, vol := range group.Volumes {
			dirs = append(dirs, vol.HostPath)
		}
		data["source_directories"] = dirs
	}

	dbHooks := g.buildDatabaseHooks(groupName, group.Databases)
	for k, v := range dbHooks {
		data[k] = v
	}

	return data
}

// engineClients maps a database type to host client binaries borgmatic will
// invoke; at least one must be present on the host for dumps to work.
var engineClients = map[string][]string{
	"postgresql": {"pg_dump"},
	"mysql":      {"mysqldump"},
	"mariadb":    {"mariadb-dump", "mysqldump"},
	dbTypeSQLite: {"sqlite3"},
}

// dbTypeSQLite entries emit a path, never a connection.
const dbTypeSQLite = "sqlite"

var engineKey = map[string]string{
	"postgresql": "postgresql_databases",
	"mysql":      "mysql_databases",
	"mariadb":    "mariadb_databases",
	dbTypeSQLite: "sqlite_databases",
}

// buildDatabaseHooks emits borgmatic database hook entries. Connection modes:
//
//   - hostname mode: the hostname label is set; emitted as hostname/port and
//     must be reachable from the host (e.g. 127.0.0.1 + published port).
//   - container mode (default): borgmatic resolves the labeled container's
//     bridge IP by name. Refused when the engine is rootless or the container
//     uses host networking, borgmatic cannot resolve an IP in either case,
//     so a config that can never work is never written.
//   - sqlite: name + host path (resolved by discovery); no connection.
func (g *Generator) buildDatabaseHooks(groupName string, dbs []models.DatabaseConfig) map[string]interface{} {
	if len(dbs) == 0 {
		return nil
	}

	grouped := make(map[string][]interface{})
	for _, db := range dbs {
		key, ok := engineKey[db.Type]
		if !ok {
			key = db.Type + "_databases"
		}

		entry := map[string]interface{}{
			"name": db.Name,
		}

		switch {
		case db.Type == dbTypeSQLite:
			entry["path"] = db.Path

		case db.Hostname != "":
			entry["hostname"] = db.Hostname
			if db.Port != 0 {
				entry["port"] = db.Port
			}

		default:
			// Container mode.
			if g.opts.Rootless {
				g.logger.Error("cannot generate container-mode database connection under a rootless engine: set the borgmatic-manager.db.N.hostname label to a host-reachable address (e.g. 127.0.0.1 with a published port)",
					"group", groupName, "database", db.Name, "container", db.Container)
				continue
			}
			if db.NetworkMode == "host" {
				g.logger.Error("cannot generate container-mode database connection for a host-network container: set the borgmatic-manager.db.N.hostname label (e.g. 127.0.0.1) instead",
					"group", groupName, "database", db.Name, "container", db.Container)
				continue
			}
			entry["container"] = db.Container
			if db.Port != 0 {
				entry["port"] = db.Port
			}
			g.warnIfMissing(groupName, db.Type, "docker", "podman")
		}

		if db.Username != "" {
			entry["username"] = db.Username
		}
		if db.Password != "" {
			entry["password"] = db.Password
		}
		if db.Options != "" {
			entry["options"] = db.Options
		}

		g.warnIfMissing(groupName, db.Type, engineClients[db.Type]...)

		grouped[key] = append(grouped[key], entry)
	}

	result := make(map[string]interface{}, len(grouped))
	for k, v := range grouped {
		result[k] = v
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

// warnIfMissing warns when none of the candidate host binaries are on PATH;
// a missing dump client is a guaranteed runtime failure.
func (g *Generator) warnIfMissing(groupName, dbType string, candidates ...string) {
	if len(candidates) == 0 {
		return
	}
	for _, bin := range candidates {
		if _, err := g.lookPath(bin); err == nil {
			return
		}
	}
	g.logger.Warn("required host binary not found on PATH; database backups for this group will fail until it is installed",
		"group", groupName, "db_type", dbType, "binaries", strings.Join(candidates, " or "))
}

// extractRepoKeys returns canonicalized repository keys: string-equal keys mean
// "same repository" for locking; unresolvable entries collapse to one conservative key.
func extractRepoKeys(final map[string]interface{}) []string {
	repos, ok := final["repositories"].([]interface{})
	if !ok {
		return nil
	}

	seen := make(map[string]bool)
	var keys []string
	for _, r := range repos {
		var path string
		switch v := r.(type) {
		case string:
			path = v
		case map[string]interface{}:
			path, _ = v["path"].(string)
		}
		if path == "" {
			continue
		}
		key := canonicalRepoKey(path)
		if !seen[key] {
			seen[key] = true
			keys = append(keys, key)
		}
	}
	return keys
}

// canonicalRepoKey normalizes a repository path for use as a lock key.
func canonicalRepoKey(path string) string {
	if strings.Contains(path, "${") {
		// Env placeholders resolve at borgmatic runtime; two spellings could
		// be the same repo. Serialize conservatively under one key.
		return "unknown"
	}
	if strings.Contains(path, "://") || strings.Contains(path, "@") {
		// Remote URL or user@host:path form.
		return strings.TrimRight(path, "/")
	}
	cleaned := filepath.Clean(path)
	if resolved, err := filepath.EvalSymlinks(cleaned); err == nil {
		return resolved
	}
	return cleaned
}

// hasSnapshotHooks reports whether the config enables any filesystem snapshot
// hook. Key presence counts: a bare `btrfs:` maps to a nil value.
func hasSnapshotHooks(final map[string]interface{}) bool {
	for _, key := range snapshotHookKeys {
		if _, ok := final[key]; ok {
			return true
		}
	}
	return false
}

// deepCopyMap creates a deep copy of a map by marshaling and unmarshaling.
func deepCopyMap(m map[string]interface{}) (map[string]interface{}, error) {
	if m == nil {
		return make(map[string]interface{}), nil
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result map[string]interface{}
	if err := yaml.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	if result == nil {
		result = make(map[string]interface{})
	}
	return result, nil
}

// writeFileAtomic writes data to a file atomically by writing to a temporary
// file in the same directory and renaming it to the final path.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".borgmatic-*.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}

	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("setting file permissions: %w", err)
	}

	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}

	return nil
}
