package config

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"gopkg.in/yaml.v3"

	"github.com/lugoues/borgmatic-manager/internal/models"
)

const headerComment = "# Auto-generated by borgmatic-manager. Do not edit.\n"

// SnapshotHookKeys are the borgmatic filesystem snapshot hooks. Groups using
// them must serialize globally: concurrent runs can destroy each other's snapshots.
var SnapshotHookKeys = []string{"btrfs", "zfs", "lvm"}

// defaultArchiveNameFormat: {group} is substituted by the manager, the rest by borg.
// Seconds resolution: an event-driven re-run lands within the same minute as
// the run before it, and borg rejects duplicate archive names (exit 30).
const defaultArchiveNameFormat = "{hostname}-{group}-{now:%Y-%m-%d_%H:%M:%S}"

// groupTokenPlaceholder is substituted with the group name. Requiring the
// literal token keeps groups sharing a repository distinguishable at prune time.
const groupTokenPlaceholder = "{group}"

// RepoRef identifies a configured repository for per-repository outcome
// tracking. Label is borgmatic's repository label (empty if unset); Path is the
// configured path/URL, matched against borgmatic's reported repository location.
type RepoRef struct {
	Path  string
	Label string
}

// GroupRunMeta is scheduling metadata extracted from a group's generated config.
type GroupRunMeta struct {
	// Repos are canonicalized repository keys. Groups sharing a key must not
	// run concurrently (Borg 1.x locks repositories exclusively).
	Repos []string
	// Repositories are the configured repositories (path + label) in config
	// order, used to attribute per-repository backup outcomes.
	Repositories []RepoRef
	// SnapshotHooks is true when the config enables btrfs/zfs/lvm hooks.
	SnapshotHooks bool
	// RunID is minted fresh each generation and stamped onto dump helper
	// containers so the runner reaps only this run's orphans.
	RunID string
	// RepositoriesKnown records that the repository list was understood in full,
	// as opposed to being absent, malformed, or holding an entry this code could
	// not read. An empty Repositories means nothing on its own.
	RepositoriesKnown bool
	// ArchivePattern matches the archive names this group's config produces,
	// with borg's date placeholders replaced by wildcards. Groups are allowed to
	// share a repository, so "the newest archive here" is not the same question
	// as "the newest archive this group wrote", and only the second one confirms
	// that this group's backup reached this repository.
	ArchivePattern string
}

// GeneratorOptions carries host-environment facts the generator needs.
type GeneratorOptions struct {
	// RuntimeDir is pinned as borgmatic's user_runtime_directory; helper dump
	// containers bind-mount it to reach borgmatic's dump FIFOs.
	RuntimeDir string
	// StateDir is pinned as borgmatic's user_state_directory (check-frequency
	// records). Relocating it makes borgmatic re-run all checks.
	StateDir string
	// ContainerCLI is the container CLI binary ("docker" or "podman") used in
	// generated helper/exec dump commands. Empty defaults to "docker".
	ContainerCLI string
}

// Generator produces per-group borgmatic YAML configuration files.
type Generator struct {
	cfg            *ManagerConfig
	groupOverrides map[string]GroupOverride
	outputDir      string
	opts           GeneratorOptions
	logger         *slog.Logger

	// lookPath is an exec.LookPath seam for testing host-dependency warnings.
	lookPath func(string) (string, error)

	// keepOvermatched skips the archive-pattern overlap refusal (pass 3).
	// Only RenderGroupForRestore sets it: an extract of an explicitly named
	// archive neither prunes nor creates, so the overlap that stops a group's
	// scheduled backups does not make its archives unrestorable.
	keepOvermatched bool
}

// NewGenerator creates a Generator. Generated files are written atomically to
// outputDir/{group}.yaml with 0600 permissions.
func NewGenerator(cfg *ManagerConfig, groupOverrides map[string]GroupOverride, outputDir string, opts GeneratorOptions, logger *slog.Logger) *Generator {
	return &Generator{
		cfg:            cfg,
		groupOverrides: groupOverrides,
		outputDir:      outputDir,
		opts:           opts,
		logger:         logger,
		lookPath:       exec.LookPath,
	}
}

// Refusal names a group that generation refused, and why.
type Refusal struct {
	Group  string
	Reason string
	// RepositoriesKnown mirrors GroupRunMeta's: whether the list was understood.
	RepositoriesKnown bool
	// Repositories are the destinations the group configures, kept even though
	// it will not run. A consumer reconciling per-repository state against the
	// current configuration needs to know what a refused group configures: it
	// never runs, so nothing else will ever tell it, and reading the refusal as
	// "this group configures nothing" is as wrong as reading it as "unknown".
	Repositories []RepoRef
}

// Generate writes a borgmatic config per group and returns scheduling metadata
// along with the groups it refused. The output directory is reconciled: configs
// for removed groups are deleted.
//
// The refusals are returned rather than only logged because a refused group
// still configures repositories, and a caller reconciling per-repository state
// has no other way to learn them: the group never runs.
func (g *Generator) Generate(state *models.BackupState) (map[string]GroupRunMeta, []Refusal, error) {
	if err := os.MkdirAll(g.outputDir, 0o700); err != nil {
		return nil, nil, fmt.Errorf("creating output directory: %w", err)
	}

	entries, refusals, err := g.plan(state, sortedGroupNames(state), newRunID)
	if err != nil {
		return nil, nil, err
	}

	// Pass 3: write the surviving configs.
	meta := make(map[string]GroupRunMeta, len(entries))
	written := make([]string, 0, len(entries))
	for _, e := range entries {
		yamlData, err := yaml.Marshal(e.final)
		if err != nil {
			return nil, nil, fmt.Errorf("marshaling config for group %s: %w", e.name, err)
		}
		output := append([]byte(headerComment), yamlData...)

		// 0600: generated configs carry credentials.
		outPath := filepath.Join(g.outputDir, e.name+".yaml")
		if err := writeFileAtomic(outPath, output, 0o600); err != nil {
			return nil, nil, fmt.Errorf("writing config for group %s: %w", e.name, err)
		}

		meta[e.name] = e.meta
		written = append(written, e.name)
	}

	if err := g.reconcile(written); err != nil {
		return nil, nil, err
	}

	return meta, refusals, nil
}

// Plan runs generation's build and safety passes without writing anything,
// returning scheduling metadata and refusals.
//
// The returned GroupRunMeta.RunID is placeholderRunID, not a real one: run IDs
// scope dump-helper reaping to one actual run, and Plan starts none. Minting a
// real one here would hand callers an identifier no helper will ever carry.
func (g *Generator) Plan(state *models.BackupState) (map[string]GroupRunMeta, []Refusal, error) {
	entries, refusals, err := g.plan(state, sortedGroupNames(state), placeholderRunIDFunc)
	if err != nil {
		return nil, nil, err
	}
	meta := make(map[string]GroupRunMeta, len(entries))
	for _, e := range entries {
		meta[e.name] = e.meta
	}
	return meta, refusals, nil
}

// RenderGroup compiles one group's config without writing. It runs the full
// plan so the shared-repo check sees every group; returns a refusal reason if
// the group was refused, and ("", "", nil) for an unknown group.
//
// Dump-helper labels carry placeholderRunID rather than a freshly minted one.
// The rendered config is what the next run will look like, not the file on
// disk, and a real-looking hex id here would read as the current run's while
// never matching it.
func (g *Generator) RenderGroup(state *models.BackupState, groupName string) (configYAML, refusal string, err error) {
	entries, refusals, err := g.plan(state, sortedGroupNames(state), placeholderRunIDFunc)
	if err != nil {
		return "", "", err
	}
	for _, r := range refusals {
		if r.Group == groupName {
			return "", r.Reason, nil
		}
	}
	for _, e := range entries {
		if e.name != groupName {
			continue
		}
		data, mErr := yaml.Marshal(e.final)
		if mErr != nil {
			return "", "", fmt.Errorf("marshaling config for group %s: %w", groupName, mErr)
		}
		return headerComment + string(data), "", nil
	}
	return "", "", nil
}

// RenderGroupForRestore renders one group's config for a restore, keeping a
// group that Generate refuses only for archive-pattern overlap: an extract of
// an explicitly named archive neither prunes nor creates, so that overlap does
// not make the group's existing archives unrestorable, and requiring a rename
// before disaster recovery could change which archives its pattern selects.
// Every other refusal still stands and comes back as the reason.
func (g *Generator) RenderGroupForRestore(state *models.BackupState, groupName string) (configYAML string, meta GroupRunMeta, reason string, err error) {
	gg := *g
	gg.keepOvermatched = true
	entries, refusals, err := gg.plan(state, sortedGroupNames(state), placeholderRunIDFunc)
	if err != nil {
		return "", GroupRunMeta{}, "", err
	}
	for _, r := range refusals {
		if r.Group == groupName {
			return "", GroupRunMeta{}, r.Reason, nil
		}
	}
	for _, e := range entries {
		if e.name != groupName {
			continue
		}
		data, mErr := yaml.Marshal(e.final)
		if mErr != nil {
			return "", GroupRunMeta{}, "", fmt.Errorf("marshaling config for group %s: %w", groupName, mErr)
		}
		return headerComment + string(data), e.meta, "", nil
	}
	return "", GroupRunMeta{}, "", nil
}

// sortedGroupNames returns the state's group names in deterministic order.
func sortedGroupNames(state *models.BackupState) []string {
	names := make([]string, 0, len(state.Groups))
	for name := range state.Groups {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// pending is one group's fully merged config awaiting the write pass.
type pending struct {
	name  string
	final map[string]interface{}
	meta  GroupRunMeta
	// groupToken: archive_name_format carried the literal {group} token before
	// substitution. Shared-repo groups need the token, not a substring match,
	// or one group's prune can delete another's archives.
	groupToken bool
}

// plan builds every group's final config in memory (pass 1) and applies
// cross-group safety checks (pass 2), returning survivors and refusals.
func (g *Generator) plan(state *models.BackupState, groupNames []string, mintRunID func() (string, error)) ([]*pending, []Refusal, error) {
	// Pass 1: build every group's final config in memory.
	entries := make([]*pending, 0, len(groupNames))

	for _, groupName := range groupNames {
		group := state.Groups[groupName]

		// 1. Deep copy global defaults via marshal/unmarshal.
		base, err := deepCopyMap(g.cfg.Borgmatic)
		if err != nil {
			return nil, nil, fmt.Errorf("copying defaults for group %s: %w", groupName, err)
		}

		// 2. Apply per-group overrides if present.
		if g.groupOverrides != nil {
			if override, ok := g.groupOverrides[groupName]; ok && override.Borgmatic != nil {
				base = DeepMerge(base, override.Borgmatic)
			}
		}

		// 2b. Apply label config fragments: labels win over files, discovered
		// data wins over both.
		for _, labelCfg := range group.LabelConfigs {
			warnLabelHooks(groupName, labelCfg, g.logger)
			base = DeepMerge(base, labelCfg)
		}

		// The borg binary is global-only: manager.yaml's local_path or "borg"
		// on PATH, validated once at launch and each cycle. A group override
		// or container label choosing its own borg is a footgun (and, from a
		// label, root code execution for anyone who can label a container),
		// so it is ignored loudly and the group runs on the default engine.
		if globalLP, _ := g.cfg.Borgmatic["local_path"].(string); true {
			if lp, _ := base["local_path"].(string); lp != "" && lp != globalLP {
				g.logger.Warn("ignoring group-level local_path: the borg binary is global-only, set it in manager.yaml",
					"group", groupName, "local_path", lp)
				if globalLP != "" {
					base["local_path"] = globalLP
				} else {
					delete(base, "local_path")
				}
			}
		}

		// 3. Build discovered data. Volume-named /./ paths are disabled when
		// snapshot hooks are enabled: borg allows only one /./ marker per path.
		runID, err := mintRunID()
		if err != nil {
			return nil, nil, fmt.Errorf("minting run id for group %s: %w", groupName, err)
		}
		discovered := g.buildDiscoveredData(groupName, group, !hasSnapshotHooks(base), runID)

		// 4. Merge discovered data on top (discovered wins).
		final := DeepMerge(base, discovered)

		// 5. Archive naming: the user's format wins when set; "{group}" is
		// substituted by the manager (all other {...} are borg placeholders).
		format, _ := final["archive_name_format"].(string)
		if format == "" {
			format = defaultArchiveNameFormat
		}
		// Record the token before substitution: pass 2 needs the literal {group}, not a substring.
		hasGroupToken := strings.Contains(format, groupTokenPlaceholder)
		final["archive_name_format"] = strings.ReplaceAll(format, groupTokenPlaceholder, groupName)
		archivePattern := archiveMatchPattern(final["archive_name_format"].(string))

		snapshotHooks := hasSnapshotHooks(final)
		repoRefs, repositoriesUnderstood := extractRepoRefs(final)

		entries = append(entries, &pending{
			name:       groupName,
			final:      final,
			groupToken: hasGroupToken,
			meta: GroupRunMeta{
				Repos:             extractRepoKeys(final),
				Repositories:      repoRefs,
				RepositoriesKnown: repositoriesUnderstood,
				SnapshotHooks:     snapshotHooks,
				ArchivePattern:    archivePattern,
				RunID:             runID,
			},
		})
	}

	// Pass 2: groups sharing a repository must keep distinguishable archive names,
	// or one group's retention (match_archives derives from the format) prunes another's.
	repoGroups := make(map[string][]string)
	for _, e := range entries {
		for _, repo := range e.meta.Repos {
			repoGroups[repo] = append(repoGroups[repo], e.name)
		}
	}

	var refusals []Refusal
	kept := entries[:0]
	for _, e := range entries {
		sharesRepo := false
		for _, repo := range e.meta.Repos {
			if len(repoGroups[repo]) > 1 {
				sharesRepo = true
				break
			}
		}
		// The token, not the resolved name: a substring match here would accept
		// "{hostname}-appdata-{now}" for both "app" and "data", leaving their
		// archives indistinguishable and letting one group's prune delete the
		// other's, the exact loss this guard exists to prevent.
		if sharesRepo && !e.groupToken {
			format, _ := e.final["archive_name_format"].(string)
			g.logger.Error("archive_name_format must contain the literal {group} token when groups share a repository, retention for one group would otherwise prune the others' archives; skipping group",
				"group", e.name, "archive_name_format", format)
			refusals = append(refusals, Refusal{
				Group:             e.name,
				Reason:            "archive_name_format must contain the {group} token when groups share a repository",
				Repositories:      e.meta.Repositories,
				RepositoriesKnown: e.meta.RepositoriesKnown,
			})
			continue
		}
		kept = append(kept, e)
	}

	// Pass 3: refuse any group whose archive pattern claims a sibling's archives
	// in a shared repository; its retention would prune them.
	//
	// Recomputed over kept rather than reusing repoGroups, which was built before
	// the refusals above. A refused group never runs, so it writes nothing to
	// contaminate a survivor's repository, and counting it here would do real
	// damage: it has no pattern or sample, which reads as "cannot be
	// distinguished" and would refuse every group merely sharing a repository
	// with it over a conflict with a group that is not running.
	keptRepoGroups := make(map[string][]string, len(repoGroups))
	patterns := make(map[string]string, len(kept))
	samples := make(map[string][]formatSegment, len(kept))
	for _, e := range kept {
		patterns[e.name] = e.meta.ArchivePattern
		format, _ := e.final["archive_name_format"].(string)
		samples[e.name] = archiveFormatSegments(format)
		for _, repo := range e.meta.Repos {
			keptRepoGroups[repo] = append(keptRepoGroups[repo], e.name)
		}
	}
	// keepOvermatched (the restore-only render) bypasses EXACTLY this overlap
	// refusal: an extract neither prunes nor creates. Every other judgment,
	// the group-borg validation below included, still applies to it — a
	// zero-exit no-op borg is as unusable for a restore as for a backup.
	if !g.keepOvermatched {
		if overmatching := overmatchingPatterns(keptRepoGroups, patterns, samples, g.logger); len(overmatching) > 0 {
			final := kept[:0]
			for _, e := range kept {
				if reason, ok := overmatching[e.name]; ok {
					refusals = append(refusals, Refusal{
						Group:             e.name,
						Reason:            reason,
						Repositories:      e.meta.Repositories,
						RepositoriesKnown: e.meta.RepositoriesKnown,
					})
					continue
				}
				final = append(final, e)
			}
			kept = final
		}
	}

	return kept, refusals, nil
}

// refuseBrokenGroupBorgs drops groups whose own borg (a non-default
// local_path) is missing, cannot run, reports no version, or sits below the
// snapshot floor while the group uses snapshot hooks. The floor stays
// advisory without hooks, matching the default borg's rules.
// hookKeys are borgmatic options that execute shell commands as the user
// running borgmatic (root under the system unit).
var hookKeys = map[string]bool{
	"commands": true, "before_actions": true, "after_actions": true,
	"before_backup": true, "after_backup": true, "before_prune": true,
	"after_prune": true, "before_check": true, "after_check": true,
	"before_compact": true, "after_compact": true, "before_extract": true,
	"after_extract": true, "on_error": true, "before_everything": true,
	"after_everything": true,
}

// warnLabelHooks flags command hooks arriving via container labels: anyone who
// can label a container makes borgmatic run them as root. Warns, never blocks.
func warnLabelHooks(groupName string, labelCfg map[string]interface{}, logger *slog.Logger) {
	for key := range labelCfg {
		if hookKeys[key] {
			logger.Warn("label-sourced config defines a command hook: it will run as the manager's user (root), anyone who can label a container controls it",
				"group", groupName, "option", key)
		}
	}
}

// reconcile removes generated configs whose groups no longer exist. Only files
// carrying the generated header are touched; operator YAML is left alone.
func (g *Generator) reconcile(current []string) error {
	keep := make(map[string]bool, len(current))
	for _, name := range current {
		keep[name+".yaml"] = true
	}

	entries, err := os.ReadDir(g.outputDir)
	if err != nil {
		return fmt.Errorf("reading output directory: %w", err)
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".yaml") || keep[name] {
			continue
		}
		path := filepath.Join(g.outputDir, name)
		if !hasGeneratedHeader(path) {
			g.logger.Warn("leaving non-generated yaml file alone in output directory", "file", name)
			continue
		}
		if err := os.Remove(path); err != nil {
			g.logger.Warn("failed to remove stale generated config", "file", name, "error", err)
			continue
		}
		g.logger.Info("removed stale generated config", "file", name)
	}
	return nil
}

// hasGeneratedHeader reports whether the file begins with the generated header comment.
func hasGeneratedHeader(path string) bool {
	f, err := os.Open(path) // #nosec G304 -- manager-owned output directory listing
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	buf := make([]byte, len(headerComment))
	n, _ := io.ReadFull(f, buf)
	return string(buf[:n]) == headerComment
}

// placeholderRunID stands in for a run identifier in configs that are compiled
// but never run: Plan's metadata and RenderGroup's display output. It is
// deliberately not hex, so it cannot be mistaken for a real id at a glance.
const placeholderRunID = "not-a-run-id-rendered-only"

// placeholderRunIDFunc is the mintRunID for those non-writing passes.
func placeholderRunIDFunc() (string, error) { return placeholderRunID, nil }

// newRunID mints a random 16-hex-char run identifier from crypto/rand.
func newRunID() (string, error) {
	buf := make([]byte, 8)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func (g *Generator) buildDiscoveredData(groupName string, group *models.VolumeGroup, volumeNamedPaths bool, runID string) map[string]interface{} {
	data := map[string]interface{}{}

	// Pin borgmatic's runtime/state dirs to the manager's own; user config can override.
	if g.opts.RuntimeDir != "" {
		data["user_runtime_directory"] = g.opts.RuntimeDir
	}
	if g.opts.StateDir != "" {
		data["user_state_directory"] = g.opts.StateDir
	}

	// Volume-named paths use borg's "/./" marker (borg >= 1.4) so archives
	// record "volA/_data/..." rather than the full /var/lib/docker path.
	if len(group.Volumes) > 0 {
		dirs := make([]interface{}, 0, len(group.Volumes))
		for _, vol := range group.Volumes {
			path := vol.HostPath
			if volumeNamedPaths {
				path = volumeNamedPath(vol.HostPath, vol.Name)
			}
			dirs = append(dirs, path)
		}
		data["source_directories"] = dirs
	}

	dbHooks := g.buildDatabaseHooks(groupName, group.Databases, runID)
	for k, v := range dbHooks {
		data[k] = v
	}

	return data
}

// engineClients maps a database type to host client binaries borgmatic will
// invoke; at least one must be present on the host for dumps to work.
var engineClients = map[string][]string{
	dbTypePostgres: {"pg_dump"},
	dbTypeMySQL:    {mysqldumpBin},
	dbTypeMariaDB:  {"mariadb-dump", mysqldumpBin},
	dbTypeSQLite:   {"sqlite3"},
}

// Database engine types. SQLite entries emit a path, never a connection.
const (
	dbTypePostgres = "postgresql"
	dbTypeMySQL    = "mysql"
	dbTypeMariaDB  = "mariadb"
	dbTypeSQLite   = "sqlite"
)

// mysqldumpBin also serves as MariaDB's fallback dump client.
const mysqldumpBin = "mysqldump"

var engineKey = map[string]string{
	dbTypePostgres: "postgresql_databases",
	dbTypeMySQL:    "mysql_databases",
	dbTypeMariaDB:  "mariadb_databases",
	dbTypeSQLite:   "sqlite_databases",
}

// buildDatabaseHooks emits borgmatic database hook entries: helper container
// (default), hostname (host client), exec (postgresql only), or sqlite (host path).
func (g *Generator) buildDatabaseHooks(groupName string, dbs []models.DatabaseConfig, runID string) map[string]interface{} {
	if len(dbs) == 0 {
		return nil
	}

	grouped := make(map[string][]interface{})
	for _, db := range dbs {
		key, ok := engineKey[db.Type]
		if !ok {
			key = db.Type + "_databases"
		}

		entry := map[string]interface{}{
			"name": db.Name,
		}

		switch {
		case db.Type == dbTypeSQLite:
			entry["path"] = db.Path
			g.warnIfMissing(groupName, db.Type, engineClients[db.Type]...)

		case db.Hostname != "":
			entry["hostname"] = db.Hostname
			if db.Port != 0 {
				entry["port"] = db.Port
			}
			g.warnIfMissing(groupName, db.Type, engineClients[db.Type]...)

		default:
			g.buildContainerClientEntry(entry, db, groupName, runID)
			g.warnIfMissing(groupName, db.Type, g.containerCLI())
		}

		if db.Username != "" {
			entry["username"] = db.Username
		}
		if db.Password != "" {
			entry["password"] = db.Password
		}
		if db.Options != "" {
			entry["options"] = db.Options
		}

		grouped[key] = append(grouped[key], entry)
	}

	result := make(map[string]interface{}, len(grouped))
	for k, v := range grouped {
		result[k] = v
	}
	if len(result) == 0 {
		return nil
	}
	return result
}

func (g *Generator) containerCLI() string {
	if g.opts.ContainerCLI != "" {
		return g.opts.ContainerCLI
	}
	return "docker"
}

// clientBinaries maps engines to (dump, interact) client binaries used in
// generated helper/exec commands.
var clientBinaries = map[string]struct{ dump, restore, interact string }{
	dbTypePostgres: {"pg_dump", "pg_restore", "psql"},
	dbTypeMySQL:    {mysqldumpBin, "mysql", "mysql"},
	dbTypeMariaDB:  {"mariadb-dump", "mariadb", "mariadb"},
}

// buildContainerClientEntry fills an entry whose client runs in a container
// (helper in the database container's netns, or exec into it). The target is
// always 127.0.0.1; the container name doubles as the borgmatic label.
func (g *Generator) buildContainerClientEntry(entry map[string]interface{}, db models.DatabaseConfig, groupName, runID string) {
	cli := g.containerCLI()
	bins := clientBinaries[db.Type]

	var base, interactive string
	if db.Mode == "exec" {
		base = fmt.Sprintf("%s exec --env PGPASSWORD %s", cli, db.Container)
		interactive = fmt.Sprintf("%s exec -i --env PGPASSWORD %s", cli, db.Container)
	} else {
		// --init: a FIFO-blocked dump client as PID 1 ignores SIGTERM and leaks
		// the container. Labels scope orphan reaping to exactly this group and run.
		run := fmt.Sprintf("%s run --rm --init --label %s=%s --label %s=%s",
			cli, models.HelperGroupLabel, groupName, models.HelperRunLabel, runID)
		if db.Type == dbTypeMySQL || db.Type == dbTypeMariaDB {
			// Mount the runtime dir at the identical path so the client reaches
			// borgmatic's dump FIFO. Shell-quoted: borgmatic word-splits these
			// commands, and a runtime dir with spaces would shred the argument.
			quoted := shellQuote(g.opts.RuntimeDir)
			run += fmt.Sprintf(" -v %s:%s", quoted, quoted)
		}
		envFlag := "--env PGPASSWORD"
		if db.Type != dbTypePostgres {
			envFlag = "--env MYSQL_PWD"
		}
		net := fmt.Sprintf("--network container:%s", db.Container)
		base = fmt.Sprintf("%s %s %s %s", run, net, envFlag, db.Image)
		interactive = fmt.Sprintf("%s -i %s %s %s", run, net, envFlag, db.Image)
	}

	entry["hostname"] = "127.0.0.1"
	if db.Port != 0 {
		entry["port"] = db.Port
	}
	entry["label"] = db.Container

	switch db.Type {
	case dbTypePostgres:
		entry["pg_dump_command"] = base + " " + bins.dump
		entry["pg_restore_command"] = interactive + " " + bins.restore
		entry["psql_command"] = interactive + " " + bins.interact
	case dbTypeMySQL:
		entry["password_transport"] = "environment"
		entry["mysql_dump_command"] = base + " " + bins.dump
		entry["mysql_command"] = interactive + " " + bins.interact
	case dbTypeMariaDB:
		entry["password_transport"] = "environment"
		entry["mariadb_dump_command"] = base + " " + bins.dump
		entry["mariadb_command"] = interactive + " " + bins.interact
	}
}

// volumeNamedPath inserts borg's "/./" marker before the volume-name component
// so archive paths start at the volume name; unmatched paths pass through unchanged.
func volumeNamedPath(hostPath, volumeName string) string {
	marker := string(filepath.Separator) + volumeName
	idx := strings.LastIndex(hostPath, marker+string(filepath.Separator))
	if idx < 0 {
		if strings.HasSuffix(hostPath, marker) {
			idx = len(hostPath) - len(marker)
		} else {
			return hostPath
		}
	}
	return hostPath[:idx] + string(filepath.Separator) + "." + hostPath[idx:]
}

// overmatchingPatterns maps each group whose archive pattern also claims a
// sibling's archives in a shared repository to its refusal reason, and logs an
// error per refused group. borgmatic derives the group's prune scope
// (match_archives) from its archive pattern, so an over-matching pattern means
// retention for one group deletes another's backups.
//
// The test is on the archive names a format generates, not on the group names
// and not on the patterns alone.
//
// Group names are the wrong question because a name check only catches the shape
// a separator happens to produce: with "{group}{now}", groups "app" and "apple"
// yield "app*" and "apple*", which collide with no separator anywhere. And a
// collision can come from the hostname rather than the group name at all, which
// is why the sample renders the placeholders whose values this host knows.
//
// Comparing two patterns as sets of strings is wrong in the other direction,
// because it asks whether any string matches both. For the common
// "{hostname}-{group}-{now}", "*-app-*" and "*-other-*" both match
// "x-app--other-y", so every pair of groups would look like a collision. What
// matters is narrower: whether one group's pattern matches a name the other
// group's format would actually generate.
//
// The decision is directional: "app-{now}" over-matches "app-prod-{now}" (its
// wildcard swallows "prod-…"), so app is refused and app-prod runs;
// "app-prod-{now}" never over-matches "app-{now}" because the literal "prod-"
// would have to come out of a timestamp. Mutual matches, including identical
// resolved formats, refuse both groups.
//
// Refusals are settled in rounds rather than one pass, because a refused group
// never runs and must not condemn anyone else. With A over-matching B in one
// repository and C over-matching only A in another, a single pass would refuse
// C for a conflict with a group that is already being dropped, and C's backups
// would stop over nothing. Each round refuses only groups that claim an
// innocent sibling (one that over-matches nobody itself), then re-evaluates
// the survivors; when every remaining conflict is between mutual offenders (a
// cycle, identical formats being the two-party case), all of them are refused.
func overmatchingPatterns(repoGroups map[string][]string, patterns map[string]string, formats map[string][]formatSegment, logger *slog.Logger) map[string]string {
	repos := make([]string, 0, len(repoGroups))
	for repo := range repoGroups {
		repos = append(repos, repo)
	}
	sort.Strings(repos)

	overmatching := map[string]string{}
	for {
		// Every over-match among the surviving groups, in deterministic order.
		type victim struct{ repo, name string }
		edges := map[string][]victim{}
		isSource := map[string]bool{}
		for _, repo := range repos {
			var groups []string
			for _, g := range repoGroups[repo] {
				if _, refused := overmatching[g]; !refused {
					groups = append(groups, g)
				}
			}
			if len(groups) < 2 {
				continue
			}
			sort.Strings(groups)
			for _, a := range groups {
				for _, b := range groups {
					if a == b || !patternOvermatches(patterns[a], formats[b]) {
						continue
					}
					edges[a] = append(edges[a], victim{repo, b})
					isSource[a] = true
				}
			}
		}
		if len(edges) == 0 {
			return overmatching
		}

		// Groups whose pattern claims an innocent sibling's archives are the
		// round's refusals. If there are none, every conflict is between
		// offenders; refuse only the cycles nothing escapes from (the sink
		// strongly connected components), so that a group merely pointing
		// INTO a cycle is re-evaluated next round against the survivors
		// instead of being dragged down with it.
		var round []string
		for name, vs := range edges {
			for _, v := range vs {
				if !isSource[v.name] {
					round = append(round, name)
					break
				}
			}
		}
		if len(round) == 0 {
			adjacency := map[string][]string{}
			for name, vs := range edges {
				for _, v := range vs {
					adjacency[name] = append(adjacency[name], v.name)
				}
			}
			round = sinkCycleMembers(adjacency)
		}
		sort.Strings(round)
		for _, name := range round {
			v := edges[name][0]
			logger.Error("archive pattern also matches a sibling group's archives in a shared repository; retention for this group would prune the sibling's backups, rename a group or split repositories; skipping group",
				"repository", v.repo, "group", name, "overlaps", v.name, "pattern", patterns[name])
			overmatching[name] = fmt.Sprintf("archive pattern %q also matches group %s's archives in a shared repository; retention would prune them", patterns[name], v.name)
		}
	}
}

// sinkCycleMembers returns the members of every strongly connected component
// with no edge leaving it. Called when every victim in the overmatch graph is
// itself an offender, so at least one such component exists and it is a cycle:
// a single group cannot overmatch itself, and a singleton whose edges all stay
// internal would have to. Refusing only these spares a group that points into
// a cycle without being part of it; once the cycle is gone, the next round
// finds its victims gone too.
func sinkCycleMembers(adjacency map[string][]string) []string {
	nodes := make([]string, 0, len(adjacency))
	for n := range adjacency {
		nodes = append(nodes, n)
	}
	sort.Strings(nodes)

	// Tarjan's algorithm, iterative-enough for these tiny graphs.
	index := map[string]int{}
	low := map[string]int{}
	onStack := map[string]bool{}
	var stack []string
	sccOf := map[string]int{}
	counter, sccCount := 0, 0

	var strongconnect func(v string)
	strongconnect = func(v string) {
		index[v] = counter
		low[v] = counter
		counter++
		stack = append(stack, v)
		onStack[v] = true
		for _, w := range adjacency[v] {
			if _, seen := index[w]; !seen {
				strongconnect(w)
				if low[w] < low[v] {
					low[v] = low[w]
				}
			} else if onStack[w] && index[w] < low[v] {
				low[v] = index[w]
			}
		}
		if low[v] == index[v] {
			for {
				w := stack[len(stack)-1]
				stack = stack[:len(stack)-1]
				onStack[w] = false
				sccOf[w] = sccCount
				if w == v {
					break
				}
			}
			sccCount++
		}
	}
	for _, n := range nodes {
		if _, seen := index[n]; !seen {
			strongconnect(n)
		}
	}

	members := map[int][]string{}
	escapes := map[int]bool{}
	for _, n := range nodes {
		members[sccOf[n]] = append(members[sccOf[n]], n)
		for _, w := range adjacency[n] {
			if sccOf[w] != sccOf[n] {
				escapes[sccOf[n]] = true
			}
		}
	}
	var out []string
	for id, ms := range members {
		if !escapes[id] && len(ms) > 1 {
			out = append(out, ms...)
		}
	}
	if len(out) == 0 {
		// Unreachable when every victim is an offender (a sink component must
		// then be a cycle), but an empty round would spin forever: refuse
		// everything rather than hang.
		out = nodes
	}
	return out
}

// patternOvermatches reports whether the pattern claims any archive name the
// format can generate. An absent pattern or format means nothing distinguishes
// that group's archives from anyone else's: treated as over-matching, which is
// the safe direction.
func patternOvermatches(pattern string, format []formatSegment) bool {
	if pattern == "" || len(format) == 0 {
		return true
	}
	return patternMatchesFormat(pattern, format)
}

// patternMatchesFormat reports whether the glob matches any name the format can
// generate.
//
// The glob is walked as a state machine over the set of positions it could be
// in, and each segment advances that set through every alternative it allows. A
// format with several directives is therefore explored in combination without
// its combinations ever being enumerated, which is what a sample of instants
// could not do.
func patternMatchesFormat(pattern string, segs []formatSegment) bool {
	states := starClosure(pattern, map[int]bool{0: true})
	for _, seg := range segs {
		if seg.any {
			// The segment is any string of the caller's choosing, so every
			// element boundary at or beyond the current states becomes
			// reachable. It is not a free pass: the remaining segments still
			// have to account for whatever the rest of the pattern demands,
			// which is what keeps pattern "foo" from claiming a format that
			// always ends in "-bar". A glob is a linear chain of elements, so
			// walking from the earliest live state visits every boundary.
			lo := len(pattern)
			for state := range states {
				if state < lo {
					lo = state
				}
			}
			next := map[int]bool{}
			for p := lo; p < len(pattern); {
				next[p] = true
				_, after := patternElement(pattern, p)
				p = after
			}
			next[len(pattern)] = true
			states = starClosure(pattern, next)
			continue
		}
		var next map[int]bool
		if seg.digits > 0 {
			next = consumeDigits(pattern, states, seg.digits)
		} else {
			next = map[int]bool{}
			for _, alt := range seg.alts {
				for state := range consume(pattern, states, alt) {
					next[state] = true
				}
			}
		}
		if len(next) == 0 {
			return false
		}
		states = next
	}
	return states[len(pattern)]
}

// consume advances every state through the literal text, one character at a
// time.
//
// Characters, not bytes: borg matches shell patterns over characters, so "?"
// covers a whole multi-byte rune. Walking bytes had it swallow only the first
// third of an "é" and declare two formats disjoint that borg would not.
func consume(pattern string, states map[int]bool, text string) map[int]bool {
	cur := states
	for _, r := range text {
		if len(cur) == 0 {
			return cur
		}
		cur = stepRune(pattern, cur, r)
	}
	return cur
}

// stepRune advances every state by one known input character.
func stepRune(pattern string, states map[int]bool, r rune) map[int]bool {
	return step(pattern, states, func(accepts func(rune) bool) bool { return accepts(r) })
}

// stepDigit advances every state by one decimal digit, whichever digit fits.
// The element decides which digits it will take, which is how a year stays a
// four-digit run even when the pattern spells it "????" or "[0-9][0-9]20".
func stepDigit(pattern string, states map[int]bool) map[int]bool {
	return step(pattern, states, func(accepts func(rune) bool) bool {
		for d := '0'; d <= '9'; d++ {
			if accepts(d) {
				return true
			}
		}
		return false
	})
}

// step advances every state by one input character. offer is given the element's
// own test and reports whether any character the caller can supply satisfies it.
func step(pattern string, states map[int]bool, offer func(accepts func(rune) bool) bool) map[int]bool {
	next := map[int]bool{}
	for state := range states {
		if state >= len(pattern) {
			continue
		}
		if pattern[state] == '*' {
			next[state] = true // the star keeps consuming
			continue
		}
		accepts, after := patternElement(pattern, state)
		if offer(accepts) {
			next[after] = true
		}
	}
	return starClosure(pattern, next)
}

// patternElement reads the matcher at i and returns the index after it. The
// returned function takes the caller's own test and reports whether any
// character satisfies both.
//
// borg matches archive names as shell patterns, so a format carrying a literal
// "?" or "[" produces a pattern that is not literal at all: "snap?app-*" claims
// a sibling's "snapXapp-..." archives. Treating those as ordinary characters
// declared such a pair disjoint while borg's own retention would not.
func patternElement(pattern string, i int) (func(rune) bool, int) {
	switch pattern[i] {
	case '?':
		return func(rune) bool { return true }, i + 1
	case '[':
		if set, after, ok := parseCharClass(pattern, i); ok {
			return set, after
		}
		// An unterminated "[" is a literal bracket, as shell globbing has it.
		return isRune('['), i + 1
	default:
		r, width := utf8.DecodeRuneInString(pattern[i:])
		return isRune(r), i + width
	}
}

func isRune(want rune) func(rune) bool {
	return func(r rune) bool { return r == want }
}

// parseCharClass reads a [...] set, honouring a leading "!" or "^" negation and
// a-z style ranges. It reports false when the class is unterminated.
func parseCharClass(pattern string, i int) (func(rune) bool, int, bool) {
	j := i + 1
	negated := false
	if j < len(pattern) && (pattern[j] == '!' || pattern[j] == '^') {
		negated = true
		j++
	}
	type span struct{ lo, hi rune }
	var spans []span
	first := true
	for j < len(pattern) {
		if pattern[j] == ']' && !first {
			set := func(r rune) bool {
				for _, sp := range spans {
					if r >= sp.lo && r <= sp.hi {
						return !negated
					}
				}
				return negated
			}
			return set, j + 1, true
		}
		first = false
		lo, width := utf8.DecodeRuneInString(pattern[j:])
		hi := lo
		next := j + width
		if next < len(pattern) && pattern[next] == '-' && next+1 < len(pattern) && pattern[next+1] != ']' {
			r, w := utf8.DecodeRuneInString(pattern[next+1:])
			hi = r
			next = next + 1 + w
		}
		if lo <= hi {
			spans = append(spans, span{lo, hi})
		}
		j = next
	}
	return nil, 0, false
}

// consumeDigits advances every state through exactly n decimal digits, whichever
// digits those turn out to be.
func consumeDigits(pattern string, states map[int]bool, n int) map[int]bool {
	cur := states
	for i := 0; i < n && len(cur) > 0; i++ {
		cur = stepDigit(pattern, cur)
	}
	return cur
}

// starClosure adds the positions reachable by letting a star match nothing.
func starClosure(pattern string, states map[int]bool) map[int]bool {
	out := make(map[int]bool, len(states))
	var add func(int)
	add = func(state int) {
		if out[state] {
			return
		}
		out[state] = true
		if state < len(pattern) && pattern[state] == '*' {
			add(state + 1)
		}
	}
	for state := range states {
		add(state)
	}
	return out
}

// archiveFormatSegments decomposes an archive_name_format into the alternatives
// each position can take, so a pattern can be tested against every name the
// format can ever generate rather than against a sample of them.
//
// Sampling cannot answer this. Each directive is small on its own, but a format
// with two of them generates their product: a group named "02-59" collides with
// a sibling formatting "{now:%m}-{now:%S}" only in February, on second 59, and
// no feasible number of sampled instants contains every such pair. Matching
// against the structure explores the combinations without enumerating them.
//
// Placeholders whose values this host knows are decomposed to those values, so a
// hostname that contains a group's name is seen. A placeholder this code cannot
// characterize becomes a segment that matches anything, which reports a
// collision rather than missing one.
func archiveFormatSegments(format string) []formatSegment {
	var out []formatSegment
	var lit strings.Builder
	flush := func() {
		if lit.Len() > 0 {
			out = append(out, formatSegment{alts: []string{lit.String()}})
			lit.Reset()
		}
	}

	depth := 0
	var token strings.Builder
	for _, r := range format {
		switch {
		case r == '{':
			depth++
			if depth == 1 {
				token.Reset()
			}
		case r == '}' && depth > 0:
			depth--
			if depth == 0 {
				flush()
				out = append(out, placeholderSegments(token.String())...)
			}
		case depth > 0:
			token.WriteRune(r)
		default:
			lit.WriteRune(r)
		}
	}
	flush()
	return out
}

// formatSegment is one position in a format: a finite set of alternatives, a run
// of digits of known length, or anything at all when the value cannot be
// characterized.
type formatSegment struct {
	alts []string
	// digits, when positive, means exactly that many decimal digits, whatever
	// they are. It is how the open-ended directives are modelled: a year has no
	// bounded set of values, and enumerating a window around today would call
	// two groups disjoint because a retained archive predates the window.
	digits int
	any    bool
}

func placeholderSegments(token string) []formatSegment {
	name, spec, hasSpec := strings.Cut(token, ":")
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "hostname":
		// borg renders the short hostname on some platforms and the full one on
		// others, and this process cannot tell which without reimplementing its
		// platform code. Both spellings are offered, so a collision through
		// either is found and neither is asserted to be the one.
		if alts := hostnameAlternatives(); len(alts) > 0 {
			return []formatSegment{{alts: alts}}
		}
	case "user", "username":
		if u := os.Getenv("USER"); u != "" {
			return []formatSegment{{alts: []string{u}}}
		}
	case "now", "utcnow":
		if !hasSpec {
			spec = "%Y-%m-%dT%H:%M:%S" // borg's default rendering of {now}
		}
		return strftimeSegments(spec)
	}
	// Everything else matches anything, which reports a collision rather than
	// missing one. That covers placeholders this code has never heard of and,
	// deliberately, {fqdn} and {reverse-hostname}: the fully qualified name comes
	// from resolver configuration and the reverse name from a PTR lookup, so a
	// value derived here could differ from what borg writes, and a wrong literal
	// is worse than none. It would declare two groups disjoint on the strength
	// of a name neither of them uses.
	return []formatSegment{{any: true}}
}

// strftimeSegments turns a strftime spec into one segment per directive, each
// carrying that directive's whole domain.
func strftimeSegments(spec string) []formatSegment {
	var out []formatSegment
	var lit strings.Builder
	flush := func() {
		if lit.Len() > 0 {
			out = append(out, formatSegment{alts: []string{lit.String()}})
			lit.Reset()
		}
	}
	for i := 0; i < len(spec); i++ {
		if spec[i] != '%' {
			lit.WriteByte(spec[i])
			continue
		}
		i++
		if i >= len(spec) {
			flush()
			return append(out, formatSegment{any: true}) // dangling percent
		}
		if spec[i] == '%' {
			lit.WriteByte('%')
			continue
		}
		flush()
		if n, ok := strftimeDigitRuns[spec[i]]; ok {
			// Open-ended: any run of that many digits. A repository outlives any
			// window of years that could be enumerated here, and its retained
			// archives still carry the year they were written in.
			out = append(out, formatSegment{digits: n})
			continue
		}
		if domain, ok := strftimeDomains[spec[i]]; ok {
			out = append(out, formatSegment{alts: domain})
			continue
		}
		// Anything else matches anything, which reports a collision rather than
		// missing one. That deliberately covers %b, %B, %a, %A and %p: those
		// render text that depends on borg's LC_TIME, so under a German locale
		// "%B" produces "Juli" and a group named "Juli" collides with a sibling
		// that formats the month by name. Enumerating them in English declared
		// such a pair disjoint, and deriving them from the effective locale would
		// be guessing at another process's environment.
		out = append(out, formatSegment{any: true})
	}
	flush()
	return out
}

// strftimeDigitRuns are the directives whose values are unbounded, given as the
// number of digits they render. Modelled as a digit run rather than a value set,
// since no enumeration of years is complete.
var strftimeDigitRuns = map[byte]int{'Y': 4, 'y': 2, 'j': 3}

// strftimeDomains is every value each supported directive can render. A
// directive that is absent renders as "anything", which collides rather than
// silently narrowing what a format can produce.
var strftimeDomains = func() map[byte][]string {
	pad := func(lo, hi int) []string {
		out := make([]string, 0, hi-lo+1)
		for v := lo; v <= hi; v++ {
			out = append(out, fmt.Sprintf("%02d", v))
		}
		return out
	}
	return map[byte][]string{
		'm': pad(1, 12), 'd': pad(1, 31),
		'H': pad(0, 23), 'I': pad(1, 12),
		'M': pad(0, 59), 'S': pad(0, 59),
	}
}()

// hostnameAlternatives lists the spellings borg's {hostname} may take on this
// host: what the kernel reports, and its short form when that carries a domain.
func hostnameAlternatives() []string {
	h := sampleHostname()
	if h == "" {
		return nil
	}
	out := []string{h}
	if short, _, found := strings.Cut(h, "."); found && short != "" {
		out = append(out, short)
	}
	return out
}

// sampleHostname is a seam: the value borg will expand {hostname} to is this
// host's, and tests need to pin it.
var sampleHostname = func() string {
	h, err := os.Hostname()
	if err != nil {
		return ""
	}
	return h
}

// warnIfMissing warns when none of the candidate host binaries are on PATH;
// a missing dump client is a guaranteed runtime failure.
func (g *Generator) warnIfMissing(groupName, dbType string, candidates ...string) {
	if len(candidates) == 0 {
		return
	}
	for _, bin := range candidates {
		if _, err := g.lookPath(bin); err == nil {
			return
		}
	}
	g.logger.Warn("required host binary not found on PATH; database backups for this group will fail until it is installed",
		"group", groupName, "db_type", dbType, "binaries", strings.Join(candidates, " or "))
}

// extractRepoKeys returns canonicalized repository keys: string-equal keys mean
// "same repository" for locking; unresolvable entries collapse to one conservative key.
func extractRepoKeys(final map[string]interface{}) []string {
	repos, ok := final["repositories"].([]interface{})
	if !ok {
		return nil
	}

	seen := make(map[string]bool)
	var keys []string
	for _, r := range repos {
		var path string
		switch v := r.(type) {
		case string:
			path = v
		case map[string]interface{}:
			path, _ = v["path"].(string)
		}
		if path == "" {
			continue
		}
		key := CanonicalRepoKey(path)
		if !seen[key] {
			seen[key] = true
			keys = append(keys, key)
		}
	}
	return keys
}

// extractRepoRefs returns the configured repositories with their labels, in
// config order, for per-repository outcome attribution.
// extractRepoRefs returns the configured repositories and whether the list was
// understood in full.
//
// The second value is not "did we find any". A malformed value, a scalar where a
// list belongs or an entry whose path is the wrong type, yields no refs for the
// same reason an empty list does, and the two must not be confused: reading a
// malformed config as "this group configures nothing" makes the reconciliation
// delete every persisted repository record, including last-success times, for a
// group whose operator was in the middle of configuring a repository.
func extractRepoRefs(final map[string]interface{}) (refs []RepoRef, understood bool) {
	raw, present := final["repositories"]
	if !present {
		return nil, true // no repositories configured is a thing a config can say
	}
	repos, ok := raw.([]interface{})
	if !ok {
		return nil, false
	}
	refs = make([]RepoRef, 0, len(repos))
	for _, r := range repos {
		switch v := r.(type) {
		case string:
			if v == "" {
				return nil, false
			}
			refs = append(refs, RepoRef{Path: v})
		case map[string]interface{}:
			path, isString := v["path"].(string)
			if !isString || path == "" {
				return nil, false
			}
			label, _ := v["label"].(string)
			refs = append(refs, RepoRef{Path: path, Label: label})
		default:
			return nil, false
		}
	}
	return refs, true
}

// shellQuote single-quotes s for a command line that borgmatic will
// word-split, escaping any embedded single quotes.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// UnknownRepoKey is the lock key for a repository path the manager cannot
// resolve, so every such repository serializes against every other.
const UnknownRepoKey = "unknown"

// CanonicalRepoKey normalizes a repository path so two spellings of the same
// repository compare equal. It is the lock key, and it is also how the runner
// correlates borgmatic's reported repository location back to the configured
// entry, which borg may report in normalized form.
//
// UnknownRepoKey is returned for a path borgmatic resolves at runtime: the
// manager cannot know what it becomes, so callers must treat it as "not
// identifiable" rather than as an identity two paths can share.
func CanonicalRepoKey(path string) string {
	if strings.Contains(path, "${") {
		// borgmatic resolves these from the environment this process hands it, so
		// a variable defined here already names the destination. Collapsing those
		// to one key serializes unrelated backups against each other and, when
		// their formats omit {group}, refuses groups that never shared anything.
		//
		// A variable this process cannot resolve keeps the conservative key: two
		// spellings might be the same repository and nothing here can tell.
		expanded := os.ExpandEnv(path)
		if expanded == "" || strings.Contains(expanded, "${") || expanded == path {
			return UnknownRepoKey
		}
		path = expanded
	}
	// An absolute path is a filesystem path, whatever punctuation it contains. A
	// directory component ending in ":" makes "/srv/a://repo" look like a URL,
	// and returning it uncleaned gave it a different lock key from "/srv/a:/repo",
	// which POSIX says is the same path: the two groups then ran concurrently
	// against one repository and skipped the shared-repository archive checks.
	if !strings.HasPrefix(path, "/") && (strings.Contains(path, "://") || isSCPStyle(path)) {
		// Remote URL or user@host:path form: nothing local to clean or resolve.
		return strings.TrimRight(path, "/")
	}
	cleaned := filepath.Clean(path)
	if resolved, err := filepath.EvalSymlinks(cleaned); err == nil {
		return resolved
	}
	return cleaned
}

// isSCPStyle reports whether a path is borg's user@host:path remote form.
//
// An at-sign alone is not the test. A local directory may contain one, and
// treating "/srv/backups@local/repo" as remote skipped the cleaning and symlink
// resolution that make two spellings of it compare equal: two groups writing to
// it as ".../repo" and "..././repo" got different keys, so they could run
// against one Borg repository concurrently and skipped the shared-repository
// archive safety checks entirely.
//
// The real shape has a colon separating host from path, with the at-sign before
// it and no path separator before either. An absolute path is never remote.
func isSCPStyle(path string) bool {
	colon := strings.Index(path, ":")
	if colon < 0 {
		return false // no host separator: a path, however many at-signs it holds
	}
	// Everything before the colon is the host part, and a host contains no path
	// separator. This is also what makes an absolute path local: it starts with
	// one, so its host part always holds a separator.
	host := path[:colon]
	if host == "" || strings.Contains(host, "/") {
		return false
	}
	// user@host:path, or host:path with no user at all, which borg also accepts.
	// An empty user or host is neither.
	at := strings.Index(host, "@")
	return at != 0 && !strings.HasSuffix(host, "@")
}

// archiveMatchPattern turns an archive_name_format into a borg match pattern by
// replacing every remaining {...} placeholder with a wildcard.
//
// The manager has already substituted {group}, so what is left is borg's own
// runtime placeholders ({now}, {hostname}, {fqdn} and friends). Replacing them
// gives a pattern matching exactly the archives this group's config writes,
// which is what distinguishes this group's archives from another group's in a
// shared repository.
func archiveMatchPattern(format string) string {
	var b strings.Builder
	depth := 0
	for _, r := range format {
		switch {
		case r == '{':
			if depth == 0 {
				b.WriteByte('*')
			}
			depth++
		case r == '}' && depth > 0:
			depth--
		case depth == 0:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// hasSnapshotHooks reports whether the config enables any filesystem snapshot
// hook. Key presence counts: a bare `btrfs:` maps to a nil value.
func hasSnapshotHooks(final map[string]interface{}) bool {
	for _, key := range SnapshotHookKeys {
		if _, ok := final[key]; ok {
			return true
		}
	}
	return false
}

// deepCopyMap creates a deep copy of a map by marshaling and unmarshaling.
func deepCopyMap(m map[string]interface{}) (map[string]interface{}, error) {
	if m == nil {
		return make(map[string]interface{}), nil
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return nil, err
	}

	var result map[string]interface{}
	if err := yaml.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	if result == nil {
		result = make(map[string]interface{})
	}
	return result, nil
}

// writeFileAtomic writes data to a file atomically by writing to a temporary
// file in the same directory and renaming it to the final path.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".borgmatic-*.tmp")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("writing temp file: %w", err)
	}

	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("setting file permissions: %w", err)
	}

	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("closing temp file: %w", err)
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("renaming temp file: %w", err)
	}

	return nil
}
